__title__ = 'civicpy'
__description__ = 'CIViC variant knowledgebase analysis toolkit.'
__url__ = 'http://civicpy.org'
__version__ = '0.0.3'
# __build__ = 0x021901
__author__ = 'Alex H. Wagner'
__author_email__ = 'ahwagner22@gmail.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2018 Alex H. Wagner'